export const projectSlides = [
    {
      img: 'carrental',
      title: 'Rental-Car',
      description: 'A Full Stack web application with user authentication and authorization. This application allows users to rent cars that are available. This website is fully functional with a search feature, likes, recent, popular, leave a comment and review, a functional booked days calendar, checkout, and an admin page. This app displays my ability to comprehensively create a beautiful front and back end that is efficient and easy to manage.',
      technologies: ['React', 'Express', 'MySQL', 'JWT', 'Redux', 'Node.js', 'Bcrypt'],
      type: 'CAR-RENTAL APPLICATION',
      link: 'https://github.com/ncortes04/Tech-Blog',
    },
     {img: 'shoppay',
    title: 'Shop-Pay',
    description: "Shop-Pay is a full-stack website that offers a convenient platform for purchasing products. This application includes user authentication, authorization, reviews, hot trends, featured products, best sellers, and checkout. The application calculates analytics based on models and routes created on the server. It also showcases my ability to quickly develop applications using Bootstrap.",
    technologies: ['React', 'Express', 'MongoDB', 'JWT', 'Redux' ],
    brief: 'Online Store For Purchasing Products',
    type: 'E-COMMERCE APPLICATION',
    link: 'https://github.com/ncortes04/shopping-avail',
  },
  {img: 'techys',
    title: 'Techy',
    description: "A full stack Blog application with user authentication and authorization. This project allows users to communicate about tech. Users can comment, view others profiles, create comments, delete comments, view their own profile, create posts, and delete posts.",
    contribution: 'This was a collaborative project in which me and 3 other classmates were assigned. We started with an idea and turned it into an application. I was in charge of the front end and helped with the back end. I created the models for Redux and handled the filtering and display of the product',
    technologies: ['React', 'Express', 'MongoDB', 'JWT', 'Sequelize'],
    brief: 'Online Blog For Tech News',
    type: "BLOG APPLICATION",
    link: 'https://github.com/ncortes04/cannabinode',
  },
  {img: 'cannabinode',
    title: 'Shop-Pay',
    description: 'A full stack E-commerce application with user authentication. This project is an online dispensary website with stripe. Users can browse the catalog and add products to their cart. A user can filter what they are looking for and checkout.',
    contribution: 'This was a collaborative project in which me and 3 other classmates were assigned. We started with an idea and turned it into an application. I was in charge of the front end and helped with the back end. I created the models for Redux and handled the filtering and display of the product',
    stack: 'This application uses the MERN stack. We chose this stack because of it was the most familiar to us at the time. There was only a few collections being used so i believe Mongo was a great choice',
    technologies: ['React', 'Express', 'MongoDB', 'JWT', 'GraphQl'],
    brief: 'Online Store For Selling Cannabis',
    type: "E-commerce",
    link: 'https://github.com/ncortes04/cannabinode',
  }
  ];
